create table if not exists public.reservations (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text not null,
  date date not null,
  time time not null,
  number_of_guests integer not null check (number_of_guests > 0),
  status text not null default 'pending' check (
    status in ('pending', 'accepted', 'rejected', 'cancelled')
  ),
  owner_notes text,
  confirmed_at timestamp with time zone,
  rejected_at timestamp with time zone,
  created_at timestamp with time zone default now()
);

alter table public.reservations
  add column if not exists status text not null default 'pending';

alter table public.reservations
  add column if not exists owner_notes text;

alter table public.reservations
  add column if not exists confirmed_at timestamp with time zone;

alter table public.reservations
  add column if not exists rejected_at timestamp with time zone;

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text unique not null,
  created_at timestamp with time zone default now()
);

alter table public.reservations enable row level security;
alter table public.admin_users enable row level security;

drop policy if exists "Allow public reservation inserts" on public.reservations;
drop policy if exists "Allow admin reservation reads" on public.reservations;
drop policy if exists "Allow admin reservation updates" on public.reservations;
drop policy if exists "Allow admin user self reads" on public.admin_users;

create policy "Allow public reservation inserts"
on public.reservations
for insert
to anon
with check (
  status = 'pending'
  and owner_notes is null
  and confirmed_at is null
  and rejected_at is null
);

create policy "Allow admin reservation reads"
on public.reservations
for select
to authenticated
using (
  exists (
    select 1
    from public.admin_users
    where admin_users.user_id = auth.uid()
  )
);

create policy "Allow admin reservation updates"
on public.reservations
for update
to authenticated
using (
  exists (
    select 1
    from public.admin_users
    where admin_users.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.admin_users
    where admin_users.user_id = auth.uid()
  )
);

create policy "Allow admin user self reads"
on public.admin_users
for select
to authenticated
using (user_id = auth.uid());
